services:
  # Backend Service
  - type: web
    name: parent-pay-pal-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: AI_SERVICE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
        
  # AI Service
  - type: web
    name: parent-pay-pal-ai
    env: python
    buildCommand: cd ai && pip install -r requirements.txt
    startCommand: cd ai && python python_service.py
    envVars:
      - key: PORT
        value: 10000
      - key: GOOGLE_API_KEY
        sync: false
      - key: CORS_ORIGIN
        sync: false